// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIGERI.Infrastructure.Persistence;

#nullable disable

namespace SIGERI.Infrastructure.Migrations
{
    [DbContext(typeof(SigeriDbContext))]
    [Migration("20260708151739_AddTratamientoFinancialFields")]
    partial class AddTratamientoFinancialFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SIGERI.Domain.Entities.Activo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Criticidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Propietario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("OrganizacionId");

                    b.ToTable("Activos", (string)null);
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.Amenaza", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CategoriaAmenazaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaAmenazaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Amenazas", (string)null);
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.CategoriaAmenaza", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasAmenaza", (string)null);
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.Control", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MitigaImpacto")
                        .HasColumnType("bit");

                    b.Property<bool>("MitigaProbabilidad")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PlanTratamientoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlanTratamientoId");

                    b.ToTable("Controles", (string)null);
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.ControlMadurez", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Funcion")
                        .HasColumnType("int");

                    b.Property<int>("NivelActual")
                        .HasColumnType("int");

                    b.Property<int>("NivelObjetivo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("ControlesMadurez", (string)null);
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.DependenciaActivo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ActivoDestinoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivoOrigenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CriticidadOperativa")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoDependencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivoDestinoId");

                    b.HasIndex("ActivoOrigenId");

                    b.ToTable("DependenciasActivos", (string)null);
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.Evaluacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ActivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActivoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Evaluaciones", (string)null);
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.HistorialRiesgoResidual", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCalculo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PuntajeOriginal")
                        .HasColumnType("int");

                    b.Property<int>("PuntajeResidual")
                        .HasColumnType("int");

                    b.Property<Guid>("RiesgoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RiesgoId");

                    b.ToTable("HistorialesRiesgoResidual", (string)null);
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.Organizacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Organizaciones", (string)null);
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.PerfilActivoCritico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ActivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContenedoresFisicos")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ContenedoresHumanos")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ContenedoresTecnicos")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImpactoFinanciero")
                        .HasColumnType("int");

                    b.Property<int>("ImpactoLegal")
                        .HasColumnType("int");

                    b.Property<int>("ImpactoProductividad")
                        .HasColumnType("int");

                    b.Property<int>("ImpactoReputacion")
                        .HasColumnType("int");

                    b.Property<int>("ImpactoSeguridadSsoma")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivoId");

                    b.ToTable("PerfilesActivosCriticos", (string)null);
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.PlanTratamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("AleBase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("CostoSalvaguarda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Estrategia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaTermino")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PorcentajeMitigacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("RiesgoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RiesgoId");

                    b.ToTable("PlanesTratamiento", (string)null);
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.Riesgo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("AmenazaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<Guid>("EvaluacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NivelRiesgo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PuntajeRiesgo")
                        .HasColumnType("int");

                    b.Property<Guid>("VulnerabilidadId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AmenazaId");

                    b.HasIndex("EvaluacionId");

                    b.HasIndex("VulnerabilidadId");

                    b.ToTable("Riesgos", (string)null);
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.Vulnerabilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SeveridadBase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Vulnerabilidades", (string)null);
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.Activo", b =>
                {
                    b.HasOne("SIGERI.Domain.Entities.Organizacion", "Organizacion")
                        .WithMany("Activos")
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.Amenaza", b =>
                {
                    b.HasOne("SIGERI.Domain.Entities.CategoriaAmenaza", "Categoria")
                        .WithMany("Amenazas")
                        .HasForeignKey("CategoriaAmenazaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.Control", b =>
                {
                    b.HasOne("SIGERI.Domain.Entities.PlanTratamiento", "PlanTratamiento")
                        .WithMany("Controles")
                        .HasForeignKey("PlanTratamientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlanTratamiento");
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.DependenciaActivo", b =>
                {
                    b.HasOne("SIGERI.Domain.Entities.Activo", "ActivoDestino")
                        .WithMany("DependenciasDestino")
                        .HasForeignKey("ActivoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGERI.Domain.Entities.Activo", "ActivoOrigen")
                        .WithMany("DependenciasOrigen")
                        .HasForeignKey("ActivoOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActivoDestino");

                    b.Navigation("ActivoOrigen");
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.Evaluacion", b =>
                {
                    b.HasOne("SIGERI.Domain.Entities.Activo", "ActivoRelacionado")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("ActivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGERI.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActivoRelacionado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.HistorialRiesgoResidual", b =>
                {
                    b.HasOne("SIGERI.Domain.Entities.Riesgo", "Riesgo")
                        .WithMany("Historiales")
                        .HasForeignKey("RiesgoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Riesgo");
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.PerfilActivoCritico", b =>
                {
                    b.HasOne("SIGERI.Domain.Entities.Activo", "ActivoRelacionado")
                        .WithMany("PerfilesCriticos")
                        .HasForeignKey("ActivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivoRelacionado");
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.PlanTratamiento", b =>
                {
                    b.HasOne("SIGERI.Domain.Entities.Riesgo", "Riesgo")
                        .WithMany("PlanesTratamiento")
                        .HasForeignKey("RiesgoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Riesgo");
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.Riesgo", b =>
                {
                    b.HasOne("SIGERI.Domain.Entities.Amenaza", "Amenaza")
                        .WithMany("Riesgos")
                        .HasForeignKey("AmenazaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGERI.Domain.Entities.Evaluacion", "Evaluacion")
                        .WithMany("Riesgos")
                        .HasForeignKey("EvaluacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGERI.Domain.Entities.Vulnerabilidad", "Vulnerabilidad")
                        .WithMany("Riesgos")
                        .HasForeignKey("VulnerabilidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("SIGERI.Domain.ValueObjects.Impacto", "Impacto", b1 =>
                        {
                            b1.Property<Guid>("RiesgoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Descripcion")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Impacto_Descripcion");

                            b1.Property<int>("Valor")
                                .HasColumnType("int")
                                .HasColumnName("Impacto_Valor");

                            b1.HasKey("RiesgoId");

                            b1.ToTable("Riesgos");

                            b1.WithOwner()
                                .HasForeignKey("RiesgoId");
                        });

                    b.OwnsOne("SIGERI.Domain.ValueObjects.Probabilidad", "Probabilidad", b1 =>
                        {
                            b1.Property<Guid>("RiesgoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Descripcion")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Probabilidad_Descripcion");

                            b1.Property<int>("Valor")
                                .HasColumnType("int")
                                .HasColumnName("Probabilidad_Valor");

                            b1.HasKey("RiesgoId");

                            b1.ToTable("Riesgos");

                            b1.WithOwner()
                                .HasForeignKey("RiesgoId");
                        });

                    b.Navigation("Amenaza");

                    b.Navigation("Evaluacion");

                    b.Navigation("Impacto")
                        .IsRequired();

                    b.Navigation("Probabilidad")
                        .IsRequired();

                    b.Navigation("Vulnerabilidad");
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.Activo", b =>
                {
                    b.Navigation("DependenciasDestino");

                    b.Navigation("DependenciasOrigen");

                    b.Navigation("Evaluaciones");

                    b.Navigation("PerfilesCriticos");
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.Amenaza", b =>
                {
                    b.Navigation("Riesgos");
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.CategoriaAmenaza", b =>
                {
                    b.Navigation("Amenazas");
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.Evaluacion", b =>
                {
                    b.Navigation("Riesgos");
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.Organizacion", b =>
                {
                    b.Navigation("Activos");
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.PlanTratamiento", b =>
                {
                    b.Navigation("Controles");
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.Riesgo", b =>
                {
                    b.Navigation("Historiales");

                    b.Navigation("PlanesTratamiento");
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Evaluaciones");
                });

            modelBuilder.Entity("SIGERI.Domain.Entities.Vulnerabilidad", b =>
                {
                    b.Navigation("Riesgos");
                });
#pragma warning restore 612, 618
        }
    }
}
